/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gambar;

import javax.swing.JFileChooser;

/**
 *
 * @author Lenovo
 */
public class GambarForm extends javax.swing.JFrame {

    private ClassGambar GambarForm;

    /**
     * Creates new form GambarForm
     */
    public GambarForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnFile = new javax.swing.JMenu();
        miBuka = new javax.swing.JMenuItem();
        miSimpan = new javax.swing.JMenuItem();
        miKeluar = new javax.swing.JMenuItem();
        mnEdit = new javax.swing.JMenu();
        miGreyscale = new javax.swing.JMenuItem();
        miBiner = new javax.swing.JMenuItem();
        miDefault = new javax.swing.JMenuItem();
        miBrightness = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        miZin = new javax.swing.JMenuItem();
        miZout = new javax.swing.JMenuItem();
        miFlipv = new javax.swing.JMenuItem();
        miFliph = new javax.swing.JMenuItem();
        miRotateRight90 = new javax.swing.JMenuItem();
        miRotateLeft90 = new javax.swing.JMenuItem();
        miRotate180 = new javax.swing.JMenuItem();
        miFreeRotate = new javax.swing.JMenuItem();
        miRotate30 = new javax.swing.JMenuItem();
        miRotate45 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jM_sharp = new javax.swing.JMenuItem();
        jM_blur = new javax.swing.JMenuItem();
        jM_Median = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PCD 1");

        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });

        jLabel2.setText("0");

        mnFile.setText("File");

        miBuka.setText("Buka");
        miBuka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miBukaActionPerformed(evt);
            }
        });
        mnFile.add(miBuka);

        miSimpan.setText("Simpan");
        miSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSimpanActionPerformed(evt);
            }
        });
        mnFile.add(miSimpan);

        miKeluar.setText("Keluar");
        miKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miKeluarActionPerformed(evt);
            }
        });
        mnFile.add(miKeluar);

        jMenuBar1.add(mnFile);

        mnEdit.setText("Edit");

        miGreyscale.setText("Greyscale");
        miGreyscale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miGreyscaleActionPerformed(evt);
            }
        });
        mnEdit.add(miGreyscale);

        miBiner.setText("Biner");
        miBiner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miBinerActionPerformed(evt);
            }
        });
        mnEdit.add(miBiner);

        miDefault.setText("Default");
        miDefault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miDefaultActionPerformed(evt);
            }
        });
        mnEdit.add(miDefault);

        miBrightness.setText("Brightness");
        miBrightness.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miBrightnessActionPerformed(evt);
            }
        });
        mnEdit.add(miBrightness);

        jMenuBar1.add(mnEdit);

        jMenu1.setText("Op. Geometri");

        miZin.setText("Zoom In");
        miZin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miZinActionPerformed(evt);
            }
        });
        jMenu1.add(miZin);

        miZout.setText("Zoom Out");
        miZout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miZoutActionPerformed(evt);
            }
        });
        jMenu1.add(miZout);

        miFlipv.setText("Flip Vertikal");
        miFlipv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miFlipvActionPerformed(evt);
            }
        });
        jMenu1.add(miFlipv);

        miFliph.setText("Flip Horizontal");
        miFliph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miFliphActionPerformed(evt);
            }
        });
        jMenu1.add(miFliph);

        miRotateRight90.setText("Rotasi Kanan 90");
        miRotateRight90.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRotateRight90ActionPerformed(evt);
            }
        });
        jMenu1.add(miRotateRight90);

        miRotateLeft90.setText("Rotasi Kiri 90");
        miRotateLeft90.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRotateLeft90ActionPerformed(evt);
            }
        });
        jMenu1.add(miRotateLeft90);

        miRotate180.setText("Rotasi 180");
        miRotate180.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRotate180ActionPerformed(evt);
            }
        });
        jMenu1.add(miRotate180);

        miFreeRotate.setText("Free Rotasi");
        miFreeRotate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miFreeRotateActionPerformed(evt);
            }
        });
        jMenu1.add(miFreeRotate);

        miRotate30.setText("Rotasi 30");
        miRotate30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRotate30ActionPerformed(evt);
            }
        });
        jMenu1.add(miRotate30);

        miRotate45.setText("Rotasi 45");
        miRotate45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRotate45ActionPerformed(evt);
            }
        });
        jMenu1.add(miRotate45);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Operasi Tetangga");

        jM_sharp.setText("Sharp");
        jM_sharp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jM_sharpActionPerformed(evt);
            }
        });
        jMenu2.add(jM_sharp);

        jM_blur.setText("Blur");
        jM_blur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jM_blurActionPerformed(evt);
            }
        });
        jMenu2.add(jM_blur);

        jM_Median.setText("Median");
        jMenu2.add(jM_Median);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(101, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miBukaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miBukaActionPerformed
        JFileChooser TDialog= new JFileChooser();
        if(TDialog.showOpenDialog(null)==JFileChooser.APPROVE_OPTION)
        {
            GambarForm = new ClassGambar(TDialog.getSelectedFile().getAbsolutePath(),355,355);
            jLabel1.setIcon(GambarForm.GetIcon());
        }
    }//GEN-LAST:event_miBukaActionPerformed

    private void miSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSimpanActionPerformed
        JFileChooser TDialog = new JFileChooser();
        if(TDialog.showSaveDialog(null) == JFileChooser.APPROVE_OPTION)
        {
            GambarForm.SaveImage(TDialog.getSelectedFile().getAbsolutePath());
            
        }
    }//GEN-LAST:event_miSimpanActionPerformed

    private void miKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miKeluarActionPerformed
        this.dispose();
    }//GEN-LAST:event_miKeluarActionPerformed

    private void miGreyscaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miGreyscaleActionPerformed
        GambarForm.Grayscale();
        jLabel1.setIcon(GambarForm.ScaleResultIcon);
    }//GEN-LAST:event_miGreyscaleActionPerformed

    private void miBinerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miBinerActionPerformed
        GambarForm.Biner();
        jLabel1.setIcon(GambarForm.ScaleResultIcon);
    }//GEN-LAST:event_miBinerActionPerformed

    private void miDefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miDefaultActionPerformed
        GambarForm.Default();
        jLabel1.setIcon(GambarForm.ScaleResultIcon);
    }//GEN-LAST:event_miDefaultActionPerformed

    private void miBrightnessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miBrightnessActionPerformed
        GambarForm.Brightness();
        jLabel1.setIcon(GambarForm.ScaleResultIcon);
    }//GEN-LAST:event_miBrightnessActionPerformed

    private void miZinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miZinActionPerformed
        GambarForm.zoomin();
        jLabel1.setIcon(GambarForm.ScaleResultIcon);
    }//GEN-LAST:event_miZinActionPerformed

    private void miZoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miZoutActionPerformed
        GambarForm.zoomout();
        jLabel1.setIcon(GambarForm.ScaleResultIcon);
    }//GEN-LAST:event_miZoutActionPerformed

    private void miFlipvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miFlipvActionPerformed
        GambarForm.flipV();
        jLabel1.setIcon(GambarForm.ScaleResultIcon);
    }//GEN-LAST:event_miFlipvActionPerformed

    private void miFliphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miFliphActionPerformed
        GambarForm.flipH();
        jLabel1.setIcon(GambarForm.ScaleResultIcon);
    }//GEN-LAST:event_miFliphActionPerformed

    private void miRotateRight90ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRotateRight90ActionPerformed
        GambarForm.rotasiCitra(90, this);
        jLabel1.setIcon(GambarForm.ScaleResultIcon);
    }//GEN-LAST:event_miRotateRight90ActionPerformed

    private void miRotateLeft90ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRotateLeft90ActionPerformed
        GambarForm.rotasiCitra(-90, this);
        jLabel1.setIcon(GambarForm.ScaleResultIcon);
    }//GEN-LAST:event_miRotateLeft90ActionPerformed

    private void miRotate180ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRotate180ActionPerformed
        GambarForm.rotasiCitra(180, this);
        jLabel1.setIcon(GambarForm.ScaleResultIcon);
    }//GEN-LAST:event_miRotate180ActionPerformed

    private void miFreeRotateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miFreeRotateActionPerformed
        jSlider1.setEnabled(true);
    }//GEN-LAST:event_miFreeRotateActionPerformed

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        GambarForm.rotasiCitra((double)jSlider1.getValue(), this);
        int a = jSlider1.getValue();
        jLabel2.setText(Integer.toString(a));
        jLabel1.setIcon(GambarForm.ScaleResultIcon);
    }//GEN-LAST:event_jSlider1StateChanged

    private void miRotate30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRotate30ActionPerformed
        GambarForm.rotasiCitra(30, this);
        jLabel1.setIcon(GambarForm.ScaleResultIcon);
    }//GEN-LAST:event_miRotate30ActionPerformed

    private void miRotate45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRotate45ActionPerformed
        GambarForm.rotasiCitra(45, this);
        jLabel1.setIcon(GambarForm.ScaleResultIcon);
    }//GEN-LAST:event_miRotate45ActionPerformed

    private void jM_sharpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jM_sharpActionPerformed
        // TODO add your handling code here:
       GambarForm.SharpenFilter();
         jLabel1.setIcon(GambarForm.ScaleResultIcon);
    }//GEN-LAST:event_jM_sharpActionPerformed

    private void jM_blurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jM_blurActionPerformed
        // TODO add your handling code here:
        GambarForm.Blur();
         jLabel1.setIcon(GambarForm.ScaleResultIcon);
    }//GEN-LAST:event_jM_blurActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GambarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GambarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GambarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GambarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GambarForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuItem jM_Median;
    private javax.swing.JMenuItem jM_blur;
    private javax.swing.JMenuItem jM_sharp;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JMenuItem miBiner;
    private javax.swing.JMenuItem miBrightness;
    private javax.swing.JMenuItem miBuka;
    private javax.swing.JMenuItem miDefault;
    private javax.swing.JMenuItem miFliph;
    private javax.swing.JMenuItem miFlipv;
    private javax.swing.JMenuItem miFreeRotate;
    private javax.swing.JMenuItem miGreyscale;
    private javax.swing.JMenuItem miKeluar;
    private javax.swing.JMenuItem miRotate180;
    private javax.swing.JMenuItem miRotate30;
    private javax.swing.JMenuItem miRotate45;
    private javax.swing.JMenuItem miRotateLeft90;
    private javax.swing.JMenuItem miRotateRight90;
    private javax.swing.JMenuItem miSimpan;
    private javax.swing.JMenuItem miZin;
    private javax.swing.JMenuItem miZout;
    private javax.swing.JMenu mnEdit;
    private javax.swing.JMenu mnFile;
    // End of variables declaration//GEN-END:variables
}
